import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../../src/components/Banner'

export default function Eynetech() {
    return (
        <main>
            <Head>
                <title>DBU | Eynetech</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Banner background={'#2F2475'} title ={"Eynetech"} subtitle ={"Branding • UI/UX"} image={"/images/eyentech/eyntech.png"}/>
            <section className='my-120'>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>About</h2>
                                <p>Eynetech is a white label partner to managed service providers (MSP), IT service companies, cloud service providers, and SAAS vendors.  It started in 2014, with an idea to help MSPs & IT service companies. They are located at Infopark, Kochi-India.</p>
                            </div>
                            <div className="work1 work3">
                                <h2>Impact</h2>
                                <p>Being one of the worlds largest MSPs, Eynetech has set a vision to become an entrusted Global White Label partner for MSPs and tech product companies whilst continuing to improve customers experience. And, in their expanding mission, we contributed our end with a strong brand identity and seamless experience for the website that set them apart from the other established industries. Now, It has its footprint globally from the US, UK, New Zealand, Ireland, and Australia.</p>
                            </div>
                            <div className="building building1">
                                <ul>
                                    <li>
                                        <h2>60k+</h2>
                                        <h3>Happy Clients</h3>
                                    </li>
                                    <li>
                                        <h2>100k+</h2>
                                        <h3>App installations</h3>
                                    </li>
                                    <li>
                                        <h2>90+ </h2>
                                        <h3>Team base</h3>
                                    </li>
                                    <li>
                                        <h2>3.5</h2>
                                        <h3>User ratings</h3>
                                    </li>
                                </ul>
                            </div>
                            <div>
                                <Image src="/images/eyentech/impact1.png" height={650} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>
                <section>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>Goal</h2>
                                <p>Creating a Mobile and Web interface for Eynetech which generates more leads by designing a feasible website that is accessed at ease and the task is performed without external distraction. An information accessible website that is highly functional and reflects the trust and authority in the audience mind and converts them for business relation</p>
                            </div>
                            <div>
                                <Image src="/images/eyentech/goal.png" height={650} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>
                <section className='my-120'>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>Discover</h2>
                                <p>Understanding certain concepts very clearly and asking certain questions with obvious answers were pertinent especially for a service like this. To develop the idea better, We tried to understand some basic concepts in depth. </p>
                            </div>
                            <div className="work1 work3">
                                <h2>User Research</h2>
                                <p>We wanted to validate the above findings by interviewing existing clients to understand what is their purpose for IT  consultants, what is their task flow, and what kind of problems they face during choosing an IT consulting firm.</p>
                            </div>
                            <div>
                                <Image src="/images/eyentech/research.png" height={650} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>

                <section className='my-120'>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>Competitive Analysis</h2>
                                <p>Since there are other consulting firms in the market we decided to do competitive research to better understand how the market works and how we can implement a design in order to reach the industry standards. 
                                    </p>
                            </div>
                            <div>
                                <Image src="/images/eyentech/analysis1.png" height={650} width={1096} />
                            </div>
                            <div>
                                <Image src="/images/eyentech/analysis2.png" height={1050} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>

                <section className='my-120'>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>Website Wireframes</h2>
                                <p>This visual guide represent skeletal framework of the website. It focuses on functionality along with how it looks. The simplicity of wireframes allowed us to quickly test ideas. 
                                   </p>
                            </div>
                            <div>
                                <Image src="/images/eyentech/wireframe.png" height={950} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>

                <section className='my-120'>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>Brand Identity*</h2>
                                <p>This visual guide represent skeletal framework of the website. It focuses on functionality along with how it looks. The simplicity of wireframes allowed us to quickly test ideas. 
                                   </p>
                            </div>
                            <div>
                                <Image src="/images/eyentech/identity.png" height={650} width={1096} />
                            </div>
                            <div>
                                <Image src="/images/eyentech/identity1.png" className='mt-5' height={650} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>

                <section className='my-120'>
                    <div className="container">
                        <div className="team">
                            <div className="work1 work3">
                                <h2>Website UI</h2>
                                <p>Earlier, the website was very vibrant. There were no real images. The typography seems way off to the design approach that we are following in our branding and marketing designs.
                                    </p>
                            </div>
                            <div>
                                <Image src="/images/eyentech/Website.png" height={4000} width={1096} />
                            </div>
                        </div>
                    </div>
                </section>

                <section className='section-margin'>
                    <div className="container">
                        <div className="clients" style={{ background: 'none' }}>
                            <Image src="/images/quote.svg" height={38} width={38} />
                            <p>Working with DBU has been a polarizing experience. DBU’s attention to detail towards the requirement is as clean as it can get. We have launched a couple of brands together, their idea and thought process has been good.
                            </p>
                            <div className='row'>
                                <Image src="/images/bakul-fresh/jobin.png" height={80} width={80} />
                                <div className="col-8">
                                    <h3>Jobin Johny</h3>
                                    <h4>Founder, Eynetech</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section>
                    <div className="next-project text-center">
                        <h3>NEXT PROJECT</h3>
                        <h1>Bakul Fresh</h1>
                        <a href="#"><i className="far fa-arrow-right" /></a>
                    </div>
                </section>
        </main>
    )
}
