import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Projects() {
    return (
        <div>
            <Head>
                <title>DBU | Projects</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section>
                <div className="container-fluid">
                    <div className="crafting text-center">
                        <h2>Crafting Industries</h2>
                        <p>We provide our clients with a fresh approach and bring innovation to their challenges.</p>
                        <ul>
                            <li className="active"><a href="#">ALL</a></li>
                            <li><a href="#">Branding</a></li>
                            <li><a href="#">UI/UX</a></li>
                            <li><a href="#">Advertising</a></li>
                        </ul>
                    </div>
                </div>
            </section>

            <section className='my-120'>
                <div className="container">
                    <div className="work">
                        <h2>Our Works</h2>
                        <p className='col-md-6 col-sm-12'>Our team of innovative thinkers and UI UX experts build results driven and user-centric designs. The work we do makes a difference, and it is this difference that drives us</p>
                    </div>
                    <div className="work-box">
                        <div className='row'>
                            <div className='col-md-6'>
                                <div className="product-wrapper spayee-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/spayee"><a><h2 className='product-wrapper--title'>Spayee</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Branding &amp; website design for an edutech startup</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/spayee"><a><Image src="/images/index/spayee.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>
                            <div className='col-md-6 '>
                                <div className="product-wrapper finshots-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/finshots"><a><h2 className='product-wrapper--title'>Finshots</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity for a financial short news application</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/finshots"><a><Image src="/images/index/finshots.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper dybo-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/dybo"><a><h2 className='product-wrapper--title'>Dybo</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Branding, UI/UX &amp; icon designs for an AR product</p>
                                    </div>
                                    <div className="content">
                                    <Link href="/projects/dybo"><a><Image src="/images/index/dybo.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper rain-pay-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/rain"><a><h2 className='product-wrapper--title'>Rain Pay</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Landing page &amp; digital ads for US based fintech product</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/rain"><a><Image src="/images/index/rain-pay.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/eynetech"><a><h2 className='product-wrapper--title'>Eynetech</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Branding &amp; website design for an IT industry</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/eynetech"><a><Image src="/images/index/eyentech.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/bakul-fresh"><a><h2 className='product-wrapper--title'>Bakul Fresh</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity &amp; app design for an agritech product</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/bakul-fresh"><a><Image src="/images/index/bakul.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/battle-xo"><a><h2 className='product-wrapper--title'>Battle XO</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Web application for a gaming platform</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/battle-xo"><a><Image src="/images/projects/Battlexo.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/vedose"><a><h2 className='product-wrapper--title'>Vedose</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity, branding &amp; website design for an E-pharma product</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/vedose"><a><Image src="/images/projects/Vedose.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/logofolio-3"><a><h2 className='product-wrapper--title'>Logofolio 3</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>2020</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/logofolio-3"><a><Image src="/images/projects/Logofolio3.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/boxfile"><a><h2 className='product-wrapper--title'>Box File</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity &amp; Website for an IT industry</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/boxfile"><a><Image src="/images/projects/Boxfile.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/cricktracker"><a><h2 className='product-wrapper--title'>Crictracker</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Collaboration with the leading cricket news website</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/cricktracker"><a><Image src="/images/projects/Crictracker.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/josh"><a><h2 className='product-wrapper--title'>Josh</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity for a social community</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/josh"><a><Image src="/images/projects/Josh.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/namalama"><a><h2 className='product-wrapper--title'>Namalama</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity &amp; packaging for an alcohol brand</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/namalama"><a><Image src="/images/projects/Namalama.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/logofolio-2"><a><h2 className='product-wrapper--title'>Logofolio 2</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>2019</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/logofolio-2"><a><Image src="/images/projects/Logofolio2.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/windo"><a><h2 className='product-wrapper--title'>Windo</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity &amp; UI/UX for an E-commerce platform</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/windo"><a><Image src="/images/projects/Windo.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg ps-0">
                                    <div className="product-wrapper--text" style={{paddingLeft: '40px'}}>
                                        <Link href="/projects/haituz"><a><h2 className='product-wrapper--title'>Haituz</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity &amp; website for edutech startup</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/haituz"><a><Image src="/images/projects/Haituz.png" width={486} height={450} layout="responsive" objectFit='cover' /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/logofolio-1"><a><h2 className='product-wrapper--title'>Logofolio 1</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>2018</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/logofolio-1"><a><Image src="/images/projects/Logofolio1.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/edulil"><a><h2 className='product-wrapper--title'>Edulil</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Brand identity &amp; website for E-learning platform for kids</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/edulil"><a><Image src="/images/projects/Edulil.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>

                            <div className='col-md-6'>
                                <div className="product-wrapper eyentech-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/intelia"><a><h2 className='product-wrapper--title'>Intelia</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>Branding &amp; website for a germany based IT startup</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/intelia"><a><Image src="/images/projects/Intelia.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>

                            </div>
                            <div className='col-md-6'>
                                <div className="product-wrapper bakul-bg">
                                    <div className="product-wrapper--text">
                                        <Link href="/projects/print-ads"><a><h2 className='product-wrapper--title'>Print Ads</h2></a></Link>
                                        <p className='product-wrapper--subtitle'>From Branding to mobile application</p>
                                    </div>
                                    <div className="content">
                                        <Link href="/projects/print-ads"><a><Image src="/images/projects/Printads.png" width={486} height={450} layout="responsive" /></a></Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}
